- hosts: all
  vars:
    jenkins_plugins:
      - credentials-binding
      - workflow-aggregator
      - docker-workflow
      - github
      - analysis-core
      - pmd
      - checkstyle
    docker_users:
      - ec2-user
      - jenkins
  roles:
    - geerlingguy.jenkins
  handlers:
    - name: restart docker
      service: name=docker state=restarted
  tasks:
    - name: installs git
      yum: name=git
    - name: installs rake
      yum: name=rake
    - name: installs docker engine
      yum: name=docker update_cache=yes
      notify:
        - restart docker
    - name: add users to docker group
      user: name={{ item }} groups=docker append=yes
      with_items: '{{ docker_users }}'
      notify:
        - restart docker
    - name: downloads get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
    - name: installs pip
      command: python /tmp/get-pip.py creates=/usr/local/bin/pip2
    - name: installs ansible-container
      pip: name=ansible-container executable=/usr/local/bin/pip2
    - name: creates link for ansible-container
      file: src=/usr/local/bin/ansible-container dest=/usr/bin/ansible-container state=link
