- hosts: all
  vars:
    jenkins_plugins:
      - workflow-aggregator
      - github-organization-folder
    docker_users:
      - ec2-user
      - jenkins
  roles:
    - geerlingguy.jenkins
  handlers:
    - name: restart docker
      service: name=docker state=restarted
  tasks:
    - name: installs git
      yum: name=git
    - name: installs docker engine
      yum: name=docker update_cache=yes
      notify:
        - restart docker
    - name: add users to docker group
      user: name={{ item }} groups=docker append=yes
      with_items: '{{ docker_users }}'